Map<String,int> color(){

  Map<String, int> lineColors = {
    'Punjabi Bagh WestShivaji Park': 1,



    //green line

    //interchnage
    'Inderlok': 11,


    //normal
    'Punjabi Bagh West': 11,
    'Shivaji Park': 1,
    'Madipur': 1,
    'Paschim Vihar East': 1,
    'Paschim Vihar West': 1,
    'Peera Garhi': 1,
    'Udyog Nagar': 1,
    'Surajmal Stadium': 1,
    'Nangloi': 1,
    'Nangloi Railway Station': 1,
    'Rajdhani Park': 1,
    'Mundka': 1,
    'Mundka Industrial Area': 1,
    'Ghevra': 1,
    'Tikri Kalan': 1,
    'Tikri Border': 1,
    'Pandit Shree Ram Sharma': 1,
    'Bahadurgarh City': 1,
    'Brigadier Hoshiyar Singh': 1,
    'Kirti Nagar':11,
    'Satguru Ram Singh Marg':1,
    'Ashok Park Main':1,



    //pink line
    'Shiv Vihar': 2,
    'Johri Enclave': 2,
    'Gokulpuri': 2,
    'Maujpur Babarpur': 2,
    'Jaffrabad': 2,
    'East Azad Nagar': 2,
    'Krishna Nagar': 2,
    'Karkarduma Court': 2,

    'IP Extension': 2,
    'Mandawali West Vinod Nagar': 2,
    'East Vinod Nagar Mayur Vihar II': 2,
    'Trilokpuri Sanjay Lake': 2,
    'Mayur Vihar Pocket I': 2,
    'Mayur Vihar I': 2,
    'Sarai Kale Khan Nizamuddin': 2,
    'Ashram': 2,
    'Vinobapuri': 2,

    'South Extension': 2,
    'INA': 11,
    'Sarojini Nagar': 2,
    'Bhikaji Cama Place': 2,
    'Sir Vishweshwaraiah Moti Bagh': 2,
    'Durgabai Deshmukh South Campus': 2,
    'Delhi Cantt': 2,
    'Naraina Vihar': 2,
    'Mayapuri': 2,

    'ESI Hospital': 2,
    'Shakurpur': 2,

    'Shalimar Bagh': 2,
    'Majlis Park': 11,


    //red  line
    "Shaheed Sthal": 3,
    "Hindon": 3,
    "Arthala": 3,
    "Mohan Nagar": 3,
    "Shyam park": 3,
    "Major Mohit Sharma": 3,
    "Raj Bagh": 3,
    "Shaheed Nagar": 3,
    "Dilshad Garden": 3,
    "Jhilmil": 3,
    "Mansarovar Park": 3,
    "Shahdara": 3,
    "Welcome":11,
    "Seelampur": 3,
    "Shastri Park": 3,
    "Kashmere Gate": 11,
    "Tis Hazari": 3,
    "Pulbangash": 3,
    "Pratap Nagar": 3,
    "Shastri Nagar": 3,
    "Kanhiya Nagar": 3,
    "Keshav Puram": 3,
    "Netaji Subhash Place": 11,
    "Kohat Enclave": 3,
    "PitamPura": 3,
    "Rohini East": 3,
    "Rohini West": 3,
    "Rithala": 3,


    //yellow
    "Samaypur Badli": 4,
    "Rohini Sector 18, 19": 4,
    "Jahangirpuri": 4,
    "Adarsh Nagar": 4,
    "Azadpur": 11,
    "Model Town": 4,
    "GTB Nagar": 4,
    "Vishwa Vidyalaya": 4,
    "Vidhan Sabha": 4,
    "Civil Lines": 4,
    "Chandni Chowk": 4,
    "Chawri Bazar": 4,

    "Patel Chowk": 4,

    "Udyog Bhawan": 4,
    "Lok Kalyan Marg": 4,
    "Jor Bagh": 4,
    "AIIMS": 4,
    "Green Park": 4,
    "Hauz Khas": 4,
    "Malviya Nagar": 4,
    "Saket": 4,
    "Qutub Minar": 4,
    "Chhatarpur": 4,
    "Sultanpur": 4,
    "Ghitorni": 4,
    "Arjan Garh": 4,
    "Guru Dronacharya": 4,
    "Sikandarpur": 4,
    "MG Road": 4,
    "IFFCO Chowk": 4,
    "Huda City Centre": 4,


    //orange
    'New Delhi': 11,
    'Shivaji Stadium': 5,
    'Dhaula Kuan': 5,
    'Delhi Aerocity': 5,
    'IGI Airport': 5,



    //violet
  "Lal Qila": 6,
  "Jama Masjid": 6,
  "Delhi Gate": 6,
  "ITO": 6,
  "Janpath": 6,
  "Central Secretariat": 11,
  "Khan Market": 6,
  "Jawaharlal Nehru Stadium": 6,
  "Jangpura": 6,
  "Lajpat Nagar": 11,
  "Moolchand": 6,
  "Kailash Colony": 6,
  "Nehru Place": 6,
  "Kalkaji Mandir": 6,
  "Govind Puri": 6,
  "Harkesh Nagar": 6,
  "Jasola Apollo": 6,
  "Sarita Vihar": 6,
  "Mohan Estate": 6,
  "Tughlakabad": 6,
  "Badarpur": 6,
  "Sarai": 6,
  "NHPC Chowk": 6,
  "Mewla Maharajpur": 6,
  "Sector 28": 6,
  "Badkhal Mor": 6,
  "Faridabad Old": 6,
  "Neelam Chowk Ajronda": 6,
  "Bata Chowk": 6,
  "Escorts Mujesar": 6,
  "Sant Surdas Sihi": 6,
  "Raja Nahar Singh Ballabhgarh": 6,

    //magneta
  "RK Ashram": 8,
  "Nabi Karim": 8,
  "Sadar Bazar": 8,
  "Pul Bangash": 8,
  "Subzi Mandi": 8,
  "Shakti Nagar Chowk": 8,
  "Derawal Nagar": 8,
  "Ashok Vihar": 8,
  "Bhalswa Lake": 8,
  "Mukarba Chowk": 8,
  "Haiderpur Badli Mor": 11,
  "North Pitampura": 8,
  "Prashant Vihar": 8,
  "Madhuban Chowk": 8,
  "Deepali Chowk": 8,
  "Pushpanjali": 8,
  "West Enclave": 8,
  "Mangolpuri": 8,
  "Peeragarhi": 8,
  "Paschim Vihar": 8,
  "Meera Bagh": 8,
  "Keshopur": 8,
  "Krishna Park Extension": 8,


    //blue
    'Vaishali': 7,
    'Kaushambi': 7,
    'Anand Vihar ISBT': 7,
    'Yamuna Bank': 7,
    'Karkarduma': 11,
    'Preet Vihar': 7,
    'Nirman Vihar': 7,
    'Laxmi Nagar': 7,
    'Noida Electronic City': 7,
    'Noida Sector 62': 7,
    'Noida Sector 59': 7,
    'Noida Sector 61': 7,
    'Noida Sector 52': 7,
    'Noida Sector 34': 7,
    'Noida City Center': 7,
    'Golf Course': 7,
    'Botanical Garden': 7,
    'Noida Sector 18': 7,
    'Noida Sector 16': 7,
    'Noida Sector 15': 7,
    'New Ashok Nagar': 7,
    'Mayur Vihar Extension': 7,
    'Mayur Vihar–I': 7,
    'Akshardham': 7,
    'Indraprastha': 7,
    'Supreme Court': 7,
    'Mandi House': 11,
    'Barakhamba Road': 7,
    'Rajiv Chowk':11,
    'Ramakrishna Ashram Marg': 7,
    'Jhandewalan': 7,
    'Karol Bagh': 7,
    'Rajendra Place': 7,
    'Patel Nagar': 7,
    'Shadipur': 7,
    'Moti Nagar': 7,
    'Ramesh Nagar': 7,
    'Rajouri Garden': 11,
    'Tagore Garden': 7,
    'Subhash Nagar': 7,
    'Tilak Nagar': 7,
    'Janakpuri East': 7,
    'Janakpuri West': 11,
    'Uttam Nagar East': 7,
    'Uttam Nagar West': 7,
    'Nawada': 7,
    'Dwarka Mor': 7,
    'Dwarka': 7,
    'Dwarka Sector 14': 7,
    'Dwarka Sector 13': 7,
    'Dwarka Sector 12': 7,
    'Dwarka Sector 11': 7,
    'Dwarka Sector 10': 7,
    'Dwarka Sector 9': 7,
    'Dwarka Sector 8': 7,
    'Dwarka Sector 21':11,

  };

  return lineColors;
}